### ISSUE TITLE
Add compatibility for Powershell Core and make this snap-in a module

### ISSUE THREAD

**Issue by semwealth** [sharefile-org/ShareFile-PowerShell#63]
Powershell versions 5.1 and earlier are no longer in active development. Powershell Core (versions 6, 7, and the future) do not support snap-ins, so the ShareFile-PowerShell SDK is totally unusable.  

This should be solvable by making it a module instead of a snap-in. Powershell Core is also based on .NET Core so there may be other considerations.

**Comment by Jhonrubia-LAS** [comment]
This is a must for the future of this SDK and seems that noone cares.
It will be easier to deploy on any enviroment.
Please make it real.

**Comment by lukeskrzypek-sf** [comment]
Please see https://github.com/sharefile-org/ShareFile-PowerShell-Module which is a port of this SnapIn to the Module format (supporting PowerShell 5.X and 7+)
