### ISSUE TITLE
[!!!] New-SfClient use WebView2 instead of WebBrowser for Form

### ISSUE THREAD

**Issue by leungjunman** [sharefile-org/ShareFile-PowerShell#77]
When running New-SfClient, it will start a Windows Form, which uses WebBrowser. This will cause it to open up an instance of IE in the form, which then pops up a JS error. This is because the web client (Internet explorer) is being refused by sharefile's site.

Updating to WebView2 will allow it to open up Edge instead of IE. It will require plugging in another event that will load a WebView2 instance, and use of async methods etc.

Additionally, it will force the updating of ancient libraries that are now vulnerable, for example Newtonsoft.JSON. Which in turn I hope will also force the Sharefile.API.Client library to be updated with a newer Newtonsoft.JSON.

**Comment by lukeskrzypek-sf** [comment]
Version v1.93 has been updated to use a WebView2 control instead of the old IE-based `WebBrowser`
